### ISSUE TITLE
The generated test examples are the same

### ISSUE THREAD

**Issue by bezsias** [laurence-bird/scalacheck-magnolia#1]
Try putting a println(person) here: 
https://github.com/laurence-bird/scalacheck-magnolia/blob/master/src/test/scala/ArbDerivationSpec.scala#L30

**Comment by laurence-bird** [comment]
Somehow this issue has passed me by. Thanks for the comment @bezsias, i'll look into this later today

**Comment by laurence-bird** [comment]
hi @bezsias,

Slightly later than I may have suggested in the previous comment but this has now been fixed in the latest commit. Thanks for calling this out :)
